### PR TITLE
Issue67 QR scanner2

### PR DESCRIPTION
**Pull request by Akohler28**
QR Scanner works as intended. Develop merged into branch.

### CODE REVIEW

**Review by shahinnezam — APPROVED** [review]
Needs work? Not sure what's happening w errors will check at school shortly

**Comment by AndrealHarrison** [comment]
I'm seeing a lot of errors in the QRcodeImageAnalyzer...

**Review by AndrealHarrison — CHANGES_REQUESTED** [review]
Problems in QRcodeImageAnalyzer should be resolved before merge

**Review by fabricekalvanda — DISMISSED** [review]

**Comment by Akohler28** [comment]
There weren't any errors when I did the commit and everything ran fine, ill check again

**Comment by AndrealHarrison** [comment]
Weird.  I just did clean project -> rebuild and I'm still seeing 33 errors in the QRcodeImageAnalyzer

**Pull request closed without merging**
